export const FETCH_NEWS_DATA = 'FETCH_NEWS_DATA';
export const FETCH_NEWS_SOURCES = 'FETCH_NEWS_SOURCES';
export const FETCH_NEWS_TRENDING = 'FETCH_NEWS_TRENDING';
export const FETCH_NEWS_SEARCH = 'FETCH_NEWS_SEARCH';
